### ISSUE TITLE
Collapse buttons are wrongly displayed

### ISSUE THREAD

**Issue by Jiiieeef** [kamranahmedse/github-diffs#1]
Nice idea but I think there is a problem: the button to open/collapse a file are hidden when the files are collapsed and the two are displayed when a file is open. (Sorry for my bad english, it's not my mother tongue, I can provide screenshot if you need)

**Comment by nilbuild** [comment]
Thank you for opening. Fixed, release is being pushed to store and will be available in a few minutes.
