### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by JobLeonard** [kamranahmedse/github-diffs#2]
Hey, I'd love to be able to use this in Firefox (without something like Chrome Store Foxified). Is there anything that would have to be done to make the extension work on both?

**Comment by nilbuild** [comment]
Hey, there is nothing chrome specific, except for the hooking it on to the page. Porting to firefox should be fairly easy

**Comment by JobLeonard** [comment]
Well I meant this as in "could you add it to the Firefox addon-store", but sure, I can give it a try too! If I'll manage I'll upload it with full credit to you and a link to this repo, yes?

**Comment by nilbuild** [comment]
Aah okay, I mistook :) yes sure, go ahead.
